apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    cpu-limit: "0.25"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "0.25"
              memory: "128Mi"
            limits:
              cpu: "0.25"
              memory: "256Mi"
          command: ["redis-server"]
          args: ["--save", "", "--appendonly", "no"]
